apiVersion: v1
kind: ServiceAccount
metadata:
   name: {{ template "serviceAccountName" . }}
{{- if .Values.image.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | trim }}
{{- end }}
