apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceAccountName" . }}
{{- if gt (len .Values.serviceAccount.iam.roleName) 0 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.jxRequirements.cluster.project }}:role/{{ template "environmentName" . }}-{{ .Values.serviceAccount.iam.roleName }}
{{- end }}
{{- if .Values.image.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | trim }}
{{- end }}
