apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  #lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts: []
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: git-clone
          resources: { }
          workingDir: /workspace
          script: |
            #!/usr/bin/env bash
            export SUBDIR="source"
            echo "git cloning url: $REPO_URL version $PULL_BASE_REF to dir: $SUBDIR"
            git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
            git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
            git config --global credential.helper store
            git clone $REPO_URL $SUBDIR
            cd $SUBDIR
            git checkout $PULL_BASE_REF
            echo "checked out revision: $PULL_BASE_REF to dir: $SUBDIR"
        - args:
          - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
          command:
          - /bin/sh
          - -c
          image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: setup-builder-home
          resources: {}
        - image: gcr.io/jenkinsxio/jx-release-version:1.0.42
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            VERSION=$(jx-release-version)-$(echo $PULL_BASE_REF | tr [:upper:] [:lower:])
            echo "Setting version to $VERSION"
            echo $VERSION > VERSION
        - image: gcr.io/jenkinsxio/jx-boot:3.1.3
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: liquidxdev.azurecr.io/golang:1.15-alpine3.12
          name: build-test
          volumeMounts:
          - mountPath: /root/.ssh_mounted/id_rsa
            name: github-ssh-keys
            subPath: id_rsa
          resources: {}
          script: |
            #!/usr/bin/env sh
            apk add git make openssh gcc g++
            git config --global url."git@github.com:".insteadOf "https://github.com/"
            mkdir -p /root/.ssh
            cp /root/.ssh_mounted/id_rsa /root/.ssh/id_rsa
            chmod 400 /root/.ssh/id_rsa
            touch /root/.ssh/known_hosts
            ssh-keyscan github.com >> /root/.ssh/known_hosts
            make test
            git config --global --unset url."git@github.com:".insteadOf
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-container-build
          volumeMounts:
          - mountPath: /root/.ssh_mounted/id_rsa
            name: github-ssh-keys
            subPath: id_rsa
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --build-arg SSH_PRIVATE_KEY="$(cat /root/.ssh_mounted/id_rsa)"
        - image: gcr.io/jenkinsxio/jx-changelog:0.0.8
          name: promote-changelog
          script: |
            #!/usr/bin/env sh
            source /workspace/source/.jx/variables.sh
            if [ -d "/workspace/source/charts/$REPO_NAME" ]; then
            sed -i -e "s/^version:.*/version: $VERSION/" ./charts/$REPO_NAME/Chart.yaml
            sed -i -e "s/repository:.*/repository: $DOCKER_REGISTRY\/$DOCKER_REGISTRY_ORG\/$APP_NAME/" ./charts/$REPO_NAME/values.yaml
            sed -i -e "s/tag:.*/tag: $VERSION/" ./charts/$REPO_NAME/values.yaml;
            else echo no charts; fi
            git commit -a -m "release $VERSION" --allow-empty
            git tag -fa v$VERSION -m "Release version $VERSION"
            git push origin v$VERSION
            jx changelog create --version v${VERSION}
        - image: gcr.io/jenkinsxio/jx-boot:3.1.3
          name: promote-helm-release
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops helm release
        volumes:
        - name: github-ssh-keys
          secret:
            secretName: github-ssh-keys
            defaultMode: 0400
            items:
            - key: filament-lqx
              path: id_rsa
        - emptyDir: {}
          name: workspace-volume
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
