{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- if hasKey .Values.metadata.ingress "annotations" }}
  annotations:
{{ toYaml .Values.metadata.ingress.annotations | trim | indent 4 }}
{{- end }}
  name: {{ template "name" . }}
spec:
  rules:
  - host: {{ template "url" . }}
    http:
      paths:
{{- $serviceName := include "name" . }}
{{- range $i, $port := .Values.service.ports }}
      - backend:
          serviceName: {{ $serviceName }}
{{- if hasKey $port "name" }}
          servicePort: {{ $port.name }}
{{- else }}
          servicePort: {{ $port.targetPort }}
{{- end }}
{{- end }}
{{- if hasKey .Values.ingress "extraURLPrefixes" }}
{{- $extraURLPrefixes := .Values.ingress.extraURLPrefixes }}
{{- $lenExtraURLPrefixes := len $extraURLPrefixes }}
{{- if gt $lenExtraURLPrefixes 0 }}
{{- range $i, $urlPrefix := .Values.ingress.extraURLPrefixes }}
  - host: {{ $urlPrefix }}{{ template "baseEnvUrl" (dict "Values" $.Values) }}
    http:
      paths:
{{- range $j, $port := $.Values.service.ports }}
      - backend:
          serviceName: {{ $serviceName }}
{{- if hasKey $port "name" }}
          servicePort: {{ $port.name }}
{{- else }}
          servicePort: {{ $port.targetPort }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if hasKey .Values.ingress "extraURLs" }}
{{- $extraURLs := .Values.ingress.extraURLs }}
{{- $lenExtraURLs := len $extraURLs }}
{{- if gt $lenExtraURLs 0 }}
{{- range $i, $url := .Values.ingress.extraURLs }}
  - host: {{ $url }}
    http:
      paths:
{{- range $j, $port := $.Values.service.ports }}
      - backend:
          serviceName: {{ $serviceName }}
{{- if hasKey $port "name" }}
          servicePort: {{ $port.name }}
{{- else }}
          servicePort: {{ $port.targetPort }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ template "url" . }}
{{- range $i, $url := .Values.ingress.extraURLs }}
    - {{ $url }}
{{- end }}
{{- range $i, $url := .Values.ingress.extraURLPrefixes }}
    - {{ $url }}{{ include "baseEnvUrl" (dict "Values" $.Values) }}
{{- end }}
    secretName: {{ template "tlsSecretName" . }}
{{- end }}
{{- end }}
