apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
{{- if hasKey .Values.metadata.deployment "labels" }}
{{ toYaml .Values.metadata.deployment.labels | trim | indent 4 }}
{{- end }}
{{- if hasKey .Values.metadata.deployment "annotations" }}
  annotations:
{{ toYaml .Values.metadata.deployment.annotations | trim | indent 4 }}
{{- end }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
{{- if hasKey .Values.metadata.deployment "labels" }}
{{ toYaml .Values.metadata.deployment.labels | trim | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
{{- if hasKey .Values.metadata.deployment "labels" }}
{{ toYaml .Values.metadata.deployment.labels | trim | indent 8 }}
{{- end }}
{{- if hasKey .Values.metadata.deployment "annotations" }}
      annotations:
{{ toYaml .Values.metadata.deployment.annotations | trim | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "serviceAccountName" . }}
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
{{ toYaml .Values.command | trim | indent 8 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if hasKey .Values.extraVolumeMounts (include "name" .) }}
{{- $extraVolumeMounts := index .Values.extraVolumeMounts (include "name" .) }}
{{- $lenExtraVolumeMounts := len $extraVolumeMounts }}
{{- if gt $lenExtraVolumeMounts 0 }}
        volumeMounts:
{{ toYaml $extraVolumeMounts | trim | indent 8 }}
{{- end }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "name" .}}-config-env
        env:
        - name: LQX_ENVIRONMENT
          value: {{ template "environmentName" . }}
{{ (include "envVars" (dict "Values" .Values "ContainerName" (include "name" .))) | trim | indent 8 }}
{{- if hasKey .Values.service "ports" }}
{{- $ports := .Values.service.ports }}
{{- $lenPorts := len $ports }}
{{- if gt $lenPorts 0 }}
        ports:
{{- range $key, $port := $ports }}
        - containerPort: {{ $port.targetPort }}
{{- if hasKey $port "name" }}
          name: {{ $port.name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if hasKey .Values "livenessProbe" }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | trim | indent 10 }}
{{- end }}
{{- if hasKey .Values "readinessProbe" }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | trim | indent 10 }}
{{- end }}
        resources:
{{ (include "resources" (dict "Values" .Values "ContainerName" (include "name" .))) | trim | indent 10 }}
{{- if hasKey .Values "extraVolumes" }}
{{- $lenExtraVolumes := len .Values.extraVolumes }}
{{- if gt $lenExtraVolumes 0 }}
      volumes:
{{ toYaml .Values.extraVolumes | trim | indent 6 }}
{{- end }}
{{- end }}
