# Global requirements
jxRequirements:
  envName: default
  ingress:
    domain: svc.cluster.local
    externalDNS: true
    namespaceSubDomain: .default.
    serviceType: ClusterIP
    tls:
      email: cicd@liquidx.com
      enabled: true
      production: true
      secretName: tls-env-wildcard

# Defines whether this should be a Deployment, Job, CronJob, or KNative Service
# options: deployment, job, cronjob, kservice
type: deployment

# Knative Service specific config options
kservice:
  containerConcurrency: 0
  timeoutSeconds: 600

# Horizontally scale the application
replicaCount: 1

# Modify metadata for different resources
metadata:
  deployment: {}
  kservice:
    annotations:
      autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
      autoscaling.knative.dev/metric: concurrency
      autoscaling.knative.dev/maxScale: "10"
      autoscaling.knative.dev/target: "1"
      ad.datadoghq.com/REPLACE_ME_APP_NAME.logs: '[{"source": "knative", "service": "REPLACE_ME_APP_NAME"}]'
  service: {}
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/limit-rpm: "600"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';";
        more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
        more_set_headers "Feature-Policy: camera 'none'; microphone 'none'; geolocation 'none'; encrypted-media 'none'; payment 'none'; speaker 'none'; usb 'none';";

# Image configuration
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
  imagePullSecrets:
  - name: tekton-container-registry-auth

# Define resources for the container
resources:
  default:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

# Provide custom env here
env:
  default:
  - name: LQX_CONFIG_PATH
    value: /etc/REPLACE_ME_APP_NAME/config;./config
  - name: DD_AGENT_SERVICE_HOST
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP
  - name: DD_AGENT_SERVICE_PORT
    value: '8126'

# Configuration for the service resource
service:
  enabled: true
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http

# Config for the liveness probe
# livenessProbe:
#   httpGet:
#     path: /healthz
#     port: 8080
#   initialDelaySeconds: 60
#   periodSeconds: 10
#   successThreshold: 1
#   timeoutSeconds: 1

# Config for the readiness probe
# readinessProbe:
#   httpGet:
#     path: /healthz
#     port: 8080
#   periodSeconds: 10
#   successThreshold: 1
#   timeoutSeconds: 1

# Fill this section if deploying a custom certificate
tls:
  certificate:
    enabled: false
    issuerName: ""
    issuerKind: ""

# Config for ingress
ingress:
  enabled: true
  extraURLs: []

# Execution command
command:
- sh
- -c
- /scripts/runwithenvironment.sh /usr/share/nginx/html/assets/data nginx

# Add any additional volumes here
extraVolumes:
- name: config-files
  secret:
    secretName: REPLACE_ME_APP_NAME-config-files
- name: vault-tls
  secret:
    secretName: vault-tls

# Add any additional volume mounts here
extraVolumeMounts:
  default:
  - name: config-files
    mountPath: /etc/REPLACE_ME_APP_NAME/config
  - name: vault-tls
    mountPath: /etc/vault/cacert
