apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  #lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone.yaml
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts: []
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: git-clone
          resources: { }
          workingDir: /workspace
          script: |
            #!/usr/bin/env bash
            export SUBDIR="source"
            echo "git cloning url: $REPO_URL version $PULL_PULL_SHA to dir: $SUBDIR"
            git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
            git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
            git config --global credential.helper store
            git clone $REPO_URL $SUBDIR
            cd $SUBDIR
            git checkout $PULL_PULL_SHA
            echo "checked out revision: $PULL_PULL_SHA to dir: $SUBDIR"
        - args:
          - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
          command:
          - /bin/sh
          - -c
          image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: setup-builder-home
          resources: {}
        - image: gcr.io/jenkinsxio/jx-boot:3.1.3
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - args:
          - npm ci
          command:
          - /bin/sh
          - -c
          image: liquidxdev.azurecr.io/node:12.18-alpine3.12
          name: build-dependencies
          volumeMounts:
          - mountPath: /tekton/home/.npmrc
            name: npmrc
            subPath: .npmrc
          resources: {}
        - args:
          - CI=true DISPLAY=:99 npm test
          command:
          - /bin/sh
          - -c
          image: liquidxdev.azurecr.io/node:12.18-alpine3.12
          name: build-test
          resources: {}
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          volumeMounts:
          - mountPath: /tekton/home/.npmrc
            name: npmrc
            subPath: .npmrc
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            cp /tekton/home/.npmrc .npmrc
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        volumes:
        - name: npmrc
          secret:
            secretName: jenkins-npm-token
            items:
            - key: token
              path: .npmrc
        - emptyDir: {}
          name: workspace-volume
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
