{{- if and .Values.service.enabled (not (eq .Values.type "kservice")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
{{- if hasKey .Values.metadata.service "labels" }}
{{ toYaml .Values.metadata.service.labels | trim | indent 4 }}
{{- end }}
{{- if hasKey .Values.metadata.service "annotations" }}
  annotations:
{{ toYaml .Values.metadata.service.annotations | trim | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | trim | indent 2}}
  selector:
    app: {{ template "name" . }}
{{- end }}
